const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const {locale,T,searchPages}=JSON.parse($('#ui-config').textContent);
const text=(key,vars={})=>String(T[key]).replace(/\{(\w+)\}/g,(_,k)=>vars[k]??`{${k}}`);
let formState=null;
try{const preferred=localStorage.getItem('khub-preview-language');if((location.pathname==='/'||location.pathname==='/index.html')&&locale==='zh'&&preferred==='en'){location.replace('en/index.html'+location.search+location.hash);}else localStorage.setItem('khub-preview-language',locale);}catch{}
function updateThemeButton(){const dark=document.documentElement.dataset.theme==='dark';$('#theme-toggle').setAttribute('aria-label',text(dark?'light':'dark'));$('#theme-toggle').title=text(dark?'light':'dark');}
updateThemeButton();$('#theme-toggle').addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('khub-preview-theme',theme);}catch{}updateThemeButton();});
$$('[data-language]').forEach(a=>{const url=new URL(a.href);url.search=location.search;url.hash=location.hash;a.href=url.href;a.addEventListener('click',event=>{if(a.dataset.language===locale){event.preventDefault();return;}try{localStorage.setItem('khub-preview-language',a.dataset.language);if(formState)sessionStorage.setItem('khub-preview-language-draft',JSON.stringify(formState()));}catch{}});});
// Markdown language links must update the preference just like the header switch.
document.addEventListener('click',event=>{const link=event.target.closest('a[href]');if(!link||link.hasAttribute('download'))return;const url=new URL(link.href);if(url.origin!==location.origin||!url.pathname.endsWith('.html')||url.pathname.includes('/raw/'))return;try{localStorage.setItem('khub-preview-language',url.pathname.includes('/en/')?'en':'zh');}catch{}});
$$('[data-md-tab]').forEach(button=>button.addEventListener('click',()=>{const source=button.dataset.mdTab==='source';$('#rendered-content').hidden=source;$('#source-content').hidden=!source;$$('[data-md-tab]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});}));
const searchDialog=$('#search-dialog');
$$('[data-open-search]').forEach(b=>b.addEventListener('click',()=>{searchDialog.showModal();$('#global-search').focus();}));
$('[data-close-search]').addEventListener('click',()=>searchDialog.close());
searchDialog.addEventListener('click',event=>{if(event.target===searchDialog)searchDialog.close();});
document.addEventListener('keydown',event=>{if(event.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)&&!searchDialog.open){event.preventDefault();searchDialog.showModal();$('#global-search').focus();}});
$('#global-search').addEventListener('input',()=>{let count=0;const q=$('#global-search').value.trim().toLocaleLowerCase();$$('[data-search-page]').forEach(a=>{a.hidden=!a.dataset.title.toLocaleLowerCase().includes(q);if(!a.hidden)count++;});$('#empty-search').hidden=count>0;});
if($('#task-search')){let filter=new URLSearchParams(location.search).get('category')||'all';const supported=$$('[data-filter]').map(x=>x.dataset.filter);if(!supported.includes(filter))filter='all';function update(){let count=0;const q=$('#task-search').value.trim().toLocaleLowerCase();$$('[data-task-row]').forEach(row=>{row.hidden=!((filter==='all'||row.dataset.category===filter)&&row.dataset.search.toLocaleLowerCase().includes(q));if(!row.hidden)count++;});$('#task-count').textContent=String(count);$('#empty-tasks').hidden=count>0;$$('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));}$('#task-search').addEventListener('input',update);$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;update();}));update();}
$$('[data-discussion-filter]').forEach(button=>button.addEventListener('click',()=>{$$('[data-discussion-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$$('[data-discussion-row]').forEach(row=>{row.hidden=button.dataset.discussionFilter!=='all'&&row.dataset.category!==button.dataset.discussionFilter;});}));
if($('#repo-search'))$('#repo-search').addEventListener('input',()=>{let count=0;const q=$('#repo-search').value.trim().toLocaleLowerCase();$$('[data-repo-row]').forEach(row=>{row.hidden=!row.dataset.search.toLocaleLowerCase().includes(q);if(!row.hidden)count++;});$('#empty-repos').hidden=count>0;if($('#repo-count'))$('#repo-count').textContent=count;});
if($('#file-search')){const folder=new URLSearchParams(location.search).get('folder');function update(){let count=0;const q=$('#file-search').value.trim().toLocaleLowerCase();$$('[data-file-row]').forEach(row=>{row.hidden=!((!folder||row.dataset.folder===folder)&&row.dataset.search.toLocaleLowerCase().includes(q));if(!row.hidden)count++;});$('#empty-files').hidden=count>0;}$('#file-search').addEventListener('input',update);update();}
if($('#draft-form')){
 fetch('data.json').then(r=>{if(!r.ok)throw Error('configuration');return r.json();}).then(({forms,tasks})=>{
  const select=$('#draft-type'),params=new URLSearchParams(location.search),form=$('#draft-form');let output='';
  const destination=params.get('destination')==='discussion'?'destinationDiscussion':'destinationIssue';
  $('#draft-destination').textContent=text(destination);
  if(forms[params.get('type')])select.value=params.get('type');
  function invalidate(){output='';$('#draft-result').hidden=true;$('#draft-empty').hidden=false;$('#copy-draft').disabled=true;$('#download-draft').disabled=true;$('#draft-status').textContent=text('waitingGenerate');$('#copy-status').textContent='';}
  function fields(){const config=forms[select.value];$('#form-heading').textContent=config.name;$('#dynamic-fields').replaceChildren();config.fields.forEach(([name,label,hint],i)=>{const wrap=document.createElement('label');wrap.className='field';const span=document.createElement('span');span.textContent=label;const area=document.createElement('textarea');area.name=name;area.id='field-'+name;area.required=i<2;area.placeholder=hint;area.maxLength=6000;wrap.append(span,area);$('#dynamic-fields').append(wrap);});invalidate();}
  fields();select.addEventListener('change',()=>{fields();$('#draft-title').value='';});form.addEventListener('input',invalidate);
  const task=tasks.find(x=>x.id===params.get('task'));if(task){$('#draft-title').value=text('interestPrefix')+task.title;$('#field-context').value=text('interestContext',{id:task.id,title:task.title});$('#field-expected').value=text('interestExpected');}
  const topic=params.get('topic');if(topic&&T[topic])$('#draft-title').value=T[topic];
  try{const raw=sessionStorage.getItem('khub-preview-language-draft');sessionStorage.removeItem('khub-preview-language-draft');if(raw){const draft=JSON.parse(raw);if(forms[draft.type]){select.value=draft.type;fields();for(const key of ['title','context','expected','extra'])if(typeof draft[key]==='string')form.elements[key].value=draft[key];}}}catch{}
  formState=()=>({type:select.value,title:form.elements.title.value,context:form.elements.context.value,expected:form.elements.expected.value,extra:form.elements.extra.value});
  form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const lines=['# '+form.elements.title.value.trim(),'','> '+text('draftDisclaimer'),'','> '+text(destination),''];forms[select.value].fields.forEach(([name,label])=>{const value=form.elements[name].value.trim();if(value)lines.push('## '+label,'',value,'');});output=lines.join('\n');$('#draft-result').textContent=output;$('#draft-result').hidden=false;$('#draft-empty').hidden=true;$('#draft-status').textContent=text('generated');$('#copy-draft').disabled=false;$('#download-draft').disabled=false;$('#copy-status').textContent=text('editHint');});
  $('#copy-draft').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(output);$('#copy-status').textContent=text('copied');}catch{$('#copy-status').textContent=text('copyFailed');}});
  $('#download-draft').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([output],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`khub-${select.value}-${locale}-draft.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#copy-status').textContent=text('downloaded');});
 }).catch(()=>{$('#form-heading').textContent=text('formError');$('#draft-form').hidden=true;$('#draft-empty').textContent=text('formErrorHint');});
}
if($('#library-search')){
 let type='all';const list=$('.library-records'),rows=$$('[data-library-record]');
 function filterLibrary(){const q=$('#library-search').value.trim().toLocaleLowerCase(),examples=$('#show-examples').checked;let count=0;rows.forEach(row=>{row.hidden=!((type==='all'||row.dataset.type===type)&&(examples||row.dataset.example!=='true')&&row.dataset.search.toLocaleLowerCase().includes(q));if(!row.hidden)count++;});$('#library-count').textContent=String(count);$('#empty-library').hidden=count>0;$$('[data-library-type]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.libraryType===type)));}
 $('#library-search').addEventListener('input',filterLibrary);$('#show-examples').addEventListener('change',filterLibrary);$$('[data-library-type]').forEach(b=>b.addEventListener('click',()=>{type=b.dataset.libraryType;filterLibrary();}));$('#library-sort').addEventListener('change',()=>{const key=$('#library-sort').value;rows.sort((a,b)=>b.dataset[key].localeCompare(a.dataset[key])||a.dataset.type.localeCompare(b.dataset.type)).forEach(row=>list.insertBefore(row,$('#empty-library')));});filterLibrary();
}
