import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {libraryUI,recordIntro} from './knowledge.mjs';
import {execFileSync} from 'node:child_process';
import {marked} from 'marked';
import {collectMaterials,encodePath,resolveContentLink} from './materials.mjs';
const base=path.dirname(fileURLToPath(import.meta.url));
const drafts=path.resolve(process.env.CONTENT_ROOT || (fs.existsSync(path.join(base,'drafts')) ? path.join(base,'drafts') : path.join(base,'..')));
const splitLayout=fs.existsSync(path.join(drafts,'community'));
const communityRoot=splitLayout?path.join(drafts,'community'):drafts;
const sourceFile=src=>splitLayout?path.join(drafts,src):src.startsWith('community/')?path.join(drafts,src.slice(10)):path.join(base,'organization-profile',src.replace('.github/',''));
const targetSite=path.resolve(process.env.SITE_OUTPUT||path.join(base,'site')),site=targetSite+'.tmp-'+process.pid;
fs.mkdirSync(site,{recursive:true});
process.on('exit',()=>{if(fs.existsSync(site))fs.rmSync(site,{recursive:true,force:true});});
const activity=JSON.parse(fs.readFileSync(path.join(base,'activity.json'),'utf8'));
const deployment=JSON.parse(fs.readFileSync(path.join(base,'deployment.json'),'utf8'));
const ui=JSON.parse(fs.readFileSync(path.join(base,'ui.json'),'utf8'));
const knowledgeRecords=JSON.parse(execFileSync(process.env.PYTHON||'python3',[path.join(base,'read-records.py'),drafts],{encoding:'utf8'}));
const recordRoute=r=>({'KH-PLAN-20260928':'knowledge-plan.html','KH-GUIDE-20260928':'record-policy.html','KH-REF-20260928':'existing-materials.html'}[r.id]||('record-'+r.id.toLowerCase()+'.html'));
const repositorySnapshot=JSON.parse(fs.readFileSync(path.join(base,'repositories.json'),'utf8'));
const taskSource=JSON.parse(fs.readFileSync(path.join(base,'tasks.json'),'utf8'));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const enSource=src=>src.replace(/\.md$/,'.en.md');
const recordGroups=new Map();
for(const r of knowledgeRecords){if(!recordGroups.has(r.id))recordGroups.set(r.id,[]);recordGroups.get(r.id).push(r);}
const recordByPath=new Map(knowledgeRecords.map(r=>[r.source_path,r.id]));
const defs=[
['routing.html','community/docs/routing.md','routing','file'],
['pilot.html','community/docs/pilot.md','pilot','file'],
['launch.html','community/docs/launch.md','launch','file'],
['org-contributing.html','.github/CONTRIBUTING.md','orgContributing','orgfile'],
['index.html','.github/profile/README.md','orgHome','org'],['community.html','community/README.md','communityHome','repo'],
['participate.html','community/docs/getting-started.md','participate','file'],['contributing.html','community/CONTRIBUTING.md','contribute','file'],
['governance.html','community/GOVERNANCE.md','governance','file'],['maintainers.html','community/MAINTAINERS.md','maintainers','file'],
['membership.html','community/MEMBERSHIP.md','membership','file'],['working.html','community/docs/working-together.md','working','file'],
['needs.html','community/docs/needs.md','needs','file'],['resources.html','community/docs/resources.md','resources','file'],
['projects.html','community/docs/projects.md','directory','file'],['discussion-guide.html','community/docs/discussions.md','discussionRules','file'],
['roadmap.html','community/ROADMAP.md','roadmap','file'],...taskSource.map(t=>[`${t.id.toLowerCase()}.html`,t.source,t.id,'issue'])
];
defs.push(['knowledge.html','community/docs/knowledge/README.md','libraryTitle','library'],...[...recordGroups.values()].map(group=>group.find(r=>r.lang==='zh')||group[0]).map(r=>[recordRoute(r),r.source_path,r.id,'record']),...['meeting','discussion','daily','decision'].map(k=>['template-'+k+'.html','community/templates/'+k+'.md','template'+k[0].toUpperCase()+k.slice(1),'file']));
const materials=collectMaterials(communityRoot);
const materialByPath=new Map(materials.documents.map(doc=>[doc.src,doc]));
const attachmentSources=new Set(materials.attachments.map(asset=>asset.src));
defs.push(...materials.documents.map(doc=>[doc.route,doc.src,doc.src,'material']));
const extraFiles=['tasks.html','discussions.html','form.html','review.html','repositories.html','people.html','board.html','pulls.html','files.html','org-board.html','org-discussions.html'];
const routes={};for(const [file,src,key,kind]of defs){
 if(kind==='record'){for(const r of recordGroups.get(key))routes[r.source_path]=(r.lang==='en'?'en/':'')+file;}
 else if(kind==='material')routes[src]=file;
 else {routes[src]=file;routes[enSource(src)]='en/'+file;}
}
const svgPaths={
 github:'<path fill="currentColor" stroke="none" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38l-.01-1.49c-2.23.48-2.7-.95-2.7-.95-.36-.92-.89-1.17-.89-1.17-.73-.5.06-.49.06-.49.8.06 1.22.82 1.22.82.71 1.21 1.87.86 2.33.66.07-.51.28-.86.51-1.06-1.78-.2-3.64-.89-3.64-3.96 0-.88.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82a7.68 7.68 0 0 1 4 0c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.08-1.87 3.75-3.65 3.95.29.25.54.74.54 1.49l-.01 2.21c0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/>',
 home:'<path d="m2 7 6-5 6 5v7H9v-4H7v4H2z"/>',repo:'<path d="M3 2h10v12H3a1 1 0 0 1 0-3h10M3 2v9M6 2v4l1-1 1 1V2"/>',
 code:'<path d="m5 4-4 4 4 4m6-8 4 4-4 4M9 2 7 14"/>',issue:'<circle cx="8" cy="8" r="6.25"/><circle cx="8" cy="8" r="1" fill="currentColor" stroke="none"/>',
 pull:'<circle cx="4" cy="3" r="1.5"/><circle cx="4" cy="13" r="1.5"/><circle cx="12" cy="13" r="1.5"/><path d="M4 4.5v7M12 11.5v-7H8m2-2-2 2 2 2"/>',
 discuss:'<path d="M1.5 2.5h10v7h-5L3 12V9.5H1.5zM7.5 12.5H11l2 2v-2h1.5v-7"/>',board:'<rect x="1.5" y="2" width="13" height="12" rx="1.5"/><path d="M6 2v12m4-12v12"/>',
 people:'<circle cx="6" cy="5" r="2.5"/><path d="M1.5 14v-2a4.5 4.5 0 0 1 9 0v2m.5-11a2.5 2.5 0 0 1 0 5m2 2a4 4 0 0 1 1.5 4"/>',
 file:'<path d="M3 1.5h6l4 4v9H3zM9 1.5v4h4"/>',folder:'<path fill="currentColor" stroke="none" d="M1 3a1 1 0 0 1 1-1h4l2 2h6a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1Z"/>',
 branch:'<circle cx="4" cy="3" r="1.5"/><circle cx="4" cy="13" r="1.5"/><circle cx="12" cy="3" r="1.5"/><path d="M4 4.5v7m8-7C12 9 4 7 4 11"/>',search:'<circle cx="6.75" cy="6.75" r="5"/><path d="m10.5 10.5 4 4"/>',
 star:'<path d="m8 1 2.1 4.4 4.9.7-3.5 3.4.8 4.8L8 12l-4.3 2.3.8-4.8L1 6.1l4.9-.7Z"/>',bell:'<path d="M3 11h10l-1-2V6a4 4 0 0 0-8 0v3ZM6 13a2 2 0 0 0 4 0"/>',
 menu:'<path d="M2 4h12M2 8h12M2 12h12"/>',chevron:'<path d="m4 6 4 4 4-4"/>',tag:'<path d="M1.5 2h6L14 8.5 8.5 14 2 7.5z"/><circle cx="5" cy="5" r=".75"/>',globe:'<circle cx="8" cy="8" r="6.3"/><ellipse cx="8" cy="8" rx="2.7" ry="6.3"/><path d="M2 6h12M2 10h12"/>',
 sun:'<circle cx="8" cy="8" r="3"/><path d="M8 0v2m0 12v2M0 8h2m12 0h2M2 2l1.5 1.5m9 9L14 14M2 14l1.5-1.5m9-9L14 2"/>',pin:'<path d="M5 2h6l-1 4 3 3H3l3-3zM8 9v6"/>',check:'<path d="m3 8 3 3 7-7"/>',arrow:'<path d="M2 8h12m-5-5 5 5-5 5"/>'
};
const icon=(name,size=16)=>`<svg class="octicon" width="${size}" height="${size}" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${svgPaths[name]||svgPaths.file}</svg>`;
for(const locale of ['zh','en']){
 const selectedRecords=[...recordGroups.values()].map(g=>g.find(r=>r.lang===locale)||g[0]);
 const T={...ui[locale],...Object.fromEntries(materials.documents.map(doc=>[doc.src,doc.title])),...Object.fromEntries(selectedRecords.map(r=>[r.id,r.title]))},t=k=>{if(!(k in T))throw Error('Missing translation '+locale+':'+k);return T[k];};
 const prefix=locale==='en'?'../':'',dir=locale==='en'?path.join(site,'en'):site;fs.mkdirSync(dir,{recursive:true});
 const tasks=taskSource.map(x=>({...x,...(locale==='en'?x.en:{}),categoryKey:({'文档':'documentation','导航':'navigation','资料':'references','体验':'usability','运营':'operations'})[x.category]}));
 const records=selectedRecords.map(r=>({...r,route:recordRoute(r),translationFallback:r.lang!==locale}));
 const forms=JSON.parse(fs.readFileSync(path.join(base,locale==='en'?'forms-en.json':'forms.json'),'utf8'));
 const sourcePath=src=>materialByPath.has(src)?src:recordByPath.has(src)?selectedRecords.find(r=>r.id===recordByPath.get(src)).source_path:locale==='en'?enSource(src):src;
 const localRoute=target=>materialByPath.has(target)?routes[target]:path.posix.relative(locale==='en'?'en':'.',routes[target]);
 function render(md,src){return marked.parse(md.replace(/^---\n[\s\S]*?\n---\n/,''),{gfm:true}).replace(/(href|src)="([^"]+)"/g,(all,attr,href)=>{
  const resolved=resolveContentLink(href,src,routes,attachmentSources);
  if(resolved?.target)return `${attr}="${escape(localRoute(resolved.target)+resolved.suffix)}"${resolved.github?` data-github-url="${href}"`:""}`;
  if(resolved?.asset)return `${attr}="${escape(prefix+'raw/'+encodePath(resolved.asset)+resolved.suffix)}"`;
  return attr==='href'&&/^https?:/.test(href)?`${all} target="_blank" rel="noopener noreferrer"`:all;
 }).replace(/<table\b([^>]*)>/g,'<div class="table-scroll"><table$1>').replace(/<\/table>/g,'</table></div>');}
 const links=[['launch.html','launch'],['routing.html','routing'],['pilot.html','pilot'],['knowledge.html','libraryTitle'],['knowledge-plan.html','knowledgePlan'],['record-policy.html','recordPolicy'],['participate.html','participate'],['contributing.html','contribute'],['governance.html','governance'],['maintainers.html','maintainers'],['membership.html','membership'],['working.html','working'],['needs.html','needs'],['resources.html','resources'],['projects.html','directory'],['roadmap.html','roadmap']];
 const searchPages=[['index.html','orgHome'],['community.html','communityHome'],['tasks.html','allIssues'],['discussions.html','discussions'],['org-board.html','orgBoard'],['board.html','board'],['repositories.html','repositories'],...links].map(([href,key])=>({href,title:t(key)}));
 const orgNav=[['index.html','overview','home'],['repositories.html','repositories','repo'],['org-discussions.html','discussions','discuss'],['org-board.html','projects','board'],['people.html','people','people']];
 const repoNav=[['community.html','code','code'],['tasks.html','issues','issue'],['pulls.html','pulls','pull'],['discussions.html','discussions','discuss'],['board.html','projects','board']];
 const button=(href,label,primary=false,ic='')=>`<a class="button ${primary?'primary':''}" href="${href}">${ic?icon(ic):''}${label}</a>`;
 function header(file,context,active){
  const langHref=locale==='en'?'../'+file:'en/'+file;
  const nav=(context==='org'?orgNav:repoNav).map(([href,key,ic])=>`<a href="${href}" ${active===key?'class="selected" aria-current="page"':''}>${icon(ic)}<span>${t(key)}</span>${key==='issues'?`<span class="counter">${tasks.length} ${t('candidate')}</span>`:''}</a>`).join('');
  return `<div class="preview-strip"><span>${t('local')}</span><a href="review.html">${t('review')}</a></div><header class="global-header"><details class="global-menu"><summary class="icon-button" aria-label="${t('menu')}">${icon('menu')}</summary><div class="menu-panel">${[['index.html','orgHome'],['community.html','communityHome'],['tasks.html','issues'],['org-discussions.html','discussions'],['org-board.html','projects']].map(([h,k])=>`<a href="${h}">${t(k)}</a>`).join('')}</div></details><a class="github-mark" href="index.html" aria-label="OpenRDHub">${icon('github',30)}</a><a class="global-owner" href="index.html">OpenRDHub</a>${context==='repo'?'<span class="slash">/</span><a class="global-repo" href="community.html">community</a>':''}<div class="global-actions"><button class="search-trigger" data-open-search aria-label="${t('searchLabel')}">${icon('search')}<span>${t('search')}</span><kbd>/</kbd></button><div class="language-switch" aria-label="${t('language')}"><a class="${locale==='zh'?'current':''}" ${locale==='zh'?'aria-current="true"':''} href="${locale==='zh'?file:langHref}" data-language="zh">中文</a><a class="${locale==='en'?'current':''}" ${locale==='en'?'aria-current="true"':''} href="${locale==='en'?file:langHref}" data-language="en">EN</a></div><button class="icon-button" id="theme-toggle" aria-label="${t('dark')}" title="${t('theme')}">${icon('sun')}</button></div></header>${context==='org'?`<section class="org-head"><div class="org-avatar" aria-label="OpenRD">Open<br>RD</div><div><h1>OpenRD</h1><p>${t('orgSummary')}</p><div class="org-meta">${icon('globe')} ${t('country')} <a href="https://github.com/OpenRDHub" target="_blank" rel="noopener noreferrer">github.com/OpenRDHub</a></div></div></section>`:`<section class="repo-head"><div class="repo-title">${icon('repo',20)}<a href="index.html">OpenRDHub</a><span>/</span><a href="community.html"><strong>community</strong></a><span class="badge">${t('repoVisibility')}</span></div><div class="repo-actions">${[['bell','notifications'],['branch','fork'],['star','star']].map(([ic,key])=>`<button class="button" disabled title="${t('unavailable')}">${icon(ic)}${t(key)}</button>`).join('')}</div></section>`}<nav class="underline-nav ${context==='org'?'org-tabs':''}" aria-label="${t(context==='org'?'organizationNav':'repositoryNav')}">${nav}</nav>`;
 }
 function footer(){return `<footer><div>${icon('github',23)}<span>${t('footer')}</span></div><nav><a href="review.html">${t('review')}</a><a href="https://github.com/OpenRDHub" target="_blank" rel="noopener noreferrer">${t('reference')}</a></nav></footer>`;}
 function shell(file,title,content,{context='repo',active='code',className=''}={}){
  const config=JSON.stringify({locale,T,searchPages}).replace(/</g,'\\u003c');
  return `<!doctype html><html lang="${locale==='zh'?'zh-CN':'en'}" data-locale="${locale}" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · OpenRDHub · ${t('local')}</title><script>try{document.documentElement.dataset.theme=localStorage.getItem('khub-preview-theme')||'light'}catch{}</script><link rel="stylesheet" href="${prefix}style.css"><script type="application/json" id="ui-config">${config}</script><script src="${prefix}app.js" defer></script></head><body><a class="skip-link" href="#main">${t('skip')}</a>${header(file,context,active)}<main id="main" class="${className}" tabindex="-1">${content}</main>${footer()}<dialog id="search-dialog"><div class="search-dialog-head">${icon('search',20)}<input id="global-search" type="search" autocomplete="off" aria-label="${t('searchLabel')}" placeholder="${t('search')}"><button class="icon-button" data-close-search aria-label="${t('close')}">×</button></div><div id="search-results">${searchPages.map(x=>`<a href="${x.href}" data-search-page data-title="${escape(x.title)}">${icon('file')}<span>${escape(x.title)}</span>${icon('arrow')}</a>`).join('')}<p id="empty-search" hidden>${t('noGlobalResults')}</p></div></dialog></body></html>`;
 }
 function about(org=false){return `<aside class="about-sidebar"><section><h2>${t(org?'people':'about')}</h2><p>${t(org?'peopleNote':'aboutText')}</p>${org?button('people.html',t('maintainers')):`<div class="topics"><a href="community.html">community</a><a href="projects.html">open-source</a><a href="needs.html">rare-disease</a></div><div class="about-links"><a href="community.html">${icon('repo')}${t('readme')}</a><a href="governance.html">${icon('file')}${t('governance')}</a><a href="maintainers.html">${icon('people')}${t('maintainers')}</a></div>`}</section><section><h2>${t(org?'communityNavigation':'phase')}</h2><p>${t(org?'homeOriginalNote':'phaseText')}</p><a href="knowledge.html">${t('libraryShortcut')} ${icon('arrow')}</a>${org?`<p><a href="repositories.html">${t('repoNavAll')} ${icon('arrow')}</a></p>`:''}</section>${org?'':`<section><h2>${t('resources')}</h2><p>${t('pending')}</p><a href="resources.html">${t('resources')}</a></section>`}</aside>`;}
 const fileItems=[['knowledge','knowledge.html','recordsFolder',true],['templates','files.html?folder=records-templates','templatesDocs',true],['.github','files.html?folder=templates','templatesFolder',true],['docs','files.html?folder=docs','docsFolder',true],['tasks','files.html?folder=tasks','tasksFolder',true],['README.md','community.html','readme',false],['CONTRIBUTING.md','contributing.html','contribute',false],['GOVERNANCE.md','governance.html','governance',false],['MAINTAINERS.md','maintainers.html','maintainers',false],['MEMBERSHIP.md','membership.html','membership',false],['ROADMAP.md','roadmap.html','roadmap',false]];
 function fileTable(){return `<div class="repo-toolbar"><details class="branch-menu"><summary class="button">${icon('branch')}main${icon('chevron')}</summary><div class="menu-panel"><strong>${t('branch')}</strong><span>${icon('check')} main · ${t('draft')}</span></div></details><span class="branch-note">${t('localBranch')}</span><a href="files.html" class="button go-file">${t('fileSearch')}</a><details class="code-menu"><summary class="button primary">${icon('code')}${t('code')}${icon('chevron')}</summary><div class="menu-panel"><p>${t('cloneNote')}</p><a href="${prefix}assets/community-drafts.zip" download>${t('downloadZip')}</a></div></details></div><div class="file-list"><div class="latest-draft"><span class="small-avatar">K</span><strong>OpenRDHub</strong><span>${t('commitNote')}</span><small>${t('draft')}</small></div>${fileItems.map(([name,href,purpose,isdir])=>`<div class="file-row"><a href="${href}">${icon(isdir?'folder':'file')}<span>${locale==='en'&&!isdir?name.replace('.md','.en.md'):name}</span></a><span>${t(purpose)}</span><small>${t('localCopy')}</small></div>`).join('')}</div>`;}
 function mdPanel(src,md,{profile=false,compact=false,action=''}={}){
  const raw=prefix+'raw/'+encodePath(src);
  return `<section class="readme-panel ${profile?'profile-readme':''} ${compact?'compact':''}"><div class="readme-toolbar"><div class="readme-tabs"><button class="active" type="button" data-md-tab="preview" aria-pressed="true">${icon('repo')}${profile?(locale==='en'?'README.en.md':'README.md'):t('preview')}</button><button type="button" data-md-tab="source" aria-pressed="false">${t('source')}</button></div><div><a href="${raw}" class="raw-link" download>${t('download')}</a></div></div><article class="markdown" id="rendered-content">${render(md,src)}${action}</article><pre class="source-view" id="source-content" hidden><code>${escape(md)}</code></pre></section>`;
 }
 function fileSidebar(current){return `<aside class="file-sidebar"><div class="sidebar-heading">${icon('repo')}<strong>${t('files')}</strong></div><div class="branch-static">${icon('branch')}main</div><nav>${fileItems.map(([name,href,key,isdir])=>`<a href="${href}" ${href===current?'class="selected" aria-current="page"':''}>${icon(isdir?'folder':'file')}<span>${locale==='en'&&!isdir?name.replace('.md','.en.md'):name}</span></a>`).join('')}<div class="side-divider"></div>${links.map(([href,key])=>`<a href="${href}" ${href===current?'class="selected" aria-current="page"':''}>${icon('file')}<span>${t(key)}</span></a>`).join('')}</nav></aside>`;}
 function issueSidebar(){return `<aside class="issue-sidebar"><a class="selected" href="tasks.html">${icon('issue')}${t('allIssues')}</a><a href="tasks.html?category=documentation">${icon('file')}${t('documentation')}</a><a href="tasks.html?category=operations">${icon('people')}${t('operations')}</a><a href="maintainers.html">${icon('people')}${t('maintainers')}</a><div class="side-divider"></div><a href="board.html">${icon('board')}${t('projects')}</a><a href="roadmap.html">${icon('pin')}${t('milestone')}</a><a href="tasks.html?labels=1">${icon('tag')}${t('labels')}</a></aside>`;}
 const categoryKeys=['all','documentation','navigation','references','usability','operations'];
 function issueRows(){return tasks.map(x=>`<a class="issue-row" href="${x.id.toLowerCase()}.html" data-task-row data-category="${x.categoryKey}" data-search="${escape(x.title+' '+x.category+' '+x.result)}">${icon('issue',18)}<div><h3>${escape(x.title)} <span class="label label-${x.categoryKey}">${escape(x.category)}</span></h3><p>${x.id} · #${x.issue_number} · ${t('remoteOpen')} · ${t('blocked')}</p></div><span class="issue-arrow">${icon('arrow')}</span></a>`).join('');}
 for(const [file,src0,key,kind] of defs){
  const src=sourcePath(src0),md=fs.readFileSync(sourceFile(src),'utf8');
  const task=tasks.find(x=>x.id===key),title=task?task.title:t(key);let html;
  if(kind==='org'){
   const content=`<div class="org-grid"><div>${mdPanel(src,md,{profile:true})}<section class="pinned-section"><h2>${t('pinned')}</h2><div class="pinned-grid"><a href="community.html" class="pinned-card">${icon('repo')}<strong>community</strong><span class="badge">${t('repoProposed')}</span><p>${t('draftRepoText')}</p></a><a href="https://github.com/OpenRDHub/rare-disease-gene-hackathon-sop" target="_blank" rel="noopener noreferrer" class="pinned-card">${icon('repo')}<strong>rare-disease-gene-hackathon-sop</strong><span class="badge">${t('existing')}</span><p>${t('sopRepoText')}</p></a></div><p><a href="repositories.html">${t('repoAll')} ${icon('arrow')}</a></p></section></div>${about(true)}</div>`;
   html=shell(file,title,content,{context:'org',active:'overview',className:'container'});
  }else if(kind==='library'){html=shell(file,title,libraryUI({t,records,icon,escape,render}),{className:'container library-container'});
  }else if(kind==='record'){const record=records.find(r=>r.source_path===src);html=shell(file,title,recordIntro({record,t,icon,escape})+mdPanel(src,md),{className:'container record-container'});
  }else if(kind==='material'){html=shell(file,title,`<div class="file-breadcrumb"><a href="files.html">${t('files')}</a> / ${escape(src.replace('community/',''))}</div>${locale==='en'?'<p class="page-hint">Chinese original · English translation is not available.</p>':''}${mdPanel(src,md)}`,{className:'container record-container'});
  }else if(kind==='repo')html=shell(file,title,`<div class="repo-grid"><div>${fileTable()}${mdPanel(src,md)}</div>${about()}</div>`,{className:'container'});
  else if(kind==='issue'){
   const body=md.replace(/^.*\n\n/,'').replace(/^# .*\n\n/,'');
   html=shell(file,title,`<div class="issue-detail-head"><h1>${escape(title)} <span>${task.id} · #${task.issue_number}</span></h1><div><span class="state-badge">${icon('issue')}${t('remoteOpen')}</span><span>${t('blocked')}</span></div></div><div class="issue-detail-grid"><div><div class="comment-box"><div class="comment-head"><span class="small-avatar">K</span><strong>OpenRDHub</strong><span>${t('issueSnapshot')}</span></div><article class="markdown">${render(body,src)}</article></div><div class="issue-next"><h2>${t('nextStep')}</h2><p>${t('taskNote')}</p>${button(task.issue_url,t('openIssue'),true)} ${button('form.html?type=proposal&task='+task.id,t('taskInterest'))}</div></div><aside class="issue-meta"><section><h2>${t('assignees')}</h2><p>${t('unassigned')}</p></section><section><h2>${t('labels')}</h2><span class="label label-${task.categoryKey}">${escape(task.category)}</span></section><section><h2>${t('milestone')}</h2><a href="roadmap.html">${t('communitySetup')}</a><p>${t('noMilestone')}</p></section><section><a href="tasks.html">${t('backIssues')}</a></section></aside></div>`,{active:'issues',className:'container issue-detail'});
  }else if(kind==='orgfile'){html=shell(file,title,`<div class="file-breadcrumb"><a href="index.html">OpenRDHub / .github</a> / CONTRIBUTING.md</div>${mdPanel(src,md)}`,{context:'org',active:'overview',className:'container record-container'});
  }else{
   let action='';const formType=file==='needs.html'?'need':file==='resources.html'?'resource':null;
   if(formType)action=`<div class="document-action">${button('form.html?type='+formType,t(formType==='need'?'tryNeed':'tryResource'),true)}<p>${t('notSent')}</p></div>`;
   html=shell(file,title,`<div class="file-layout">${fileSidebar(file)}<section class="file-content"><div class="file-breadcrumb"><a href="community.html">community</a><span>/</span><strong>${escape(src.replace('community/',''))}</strong></div><div class="file-status">${icon('file')}${t('draftNotice')}</div>${mdPanel(src,md,{compact:true,action})}</section></div>`,{className:'wide-container'});
  }
  fs.writeFileSync(path.join(dir,file),html);
 }
 const issues=`<div class="issues-layout">${issueSidebar()}<section class="issues-content"><div class="section-title"><h1>${t('allIssues')}</h1>${button('form.html?type=proposal',t('newIssue'),true)}</div><p class="page-hint">${t('issueHint')}</p><p>${button(deployment.repository_url+'/issues',t('openIssues'))} ${button(deployment.project_url,t('openBoard'))}</p>${deployment.issue_url?`<p><a href="${deployment.issue_url}" target="_blank" rel="noopener noreferrer">${t('pilotIssue')}</a></p>`:''}<label class="issue-search">${icon('search')}<input type="search" id="task-search" aria-label="${t('filterSearch')}" placeholder="${t('filterSearch')}"><kbd>/</kbd></label><div class="issue-filter-row">${categoryKeys.map((k,i)=>`<button data-filter="${k}" aria-pressed="${i===0}">${t(k)}</button>`).join('')}</div><div class="issue-list"><div class="issue-list-head"><strong>${icon('issue')}${t('issueDrafts')} <span id="task-count">6</span></strong><span>${t('blocked')}</span></div>${issueRows()}<div class="empty-state" id="empty-tasks" hidden>${t('noResults')}</div></div></section></div>`;
 fs.writeFileSync(path.join(dir,'tasks.html'),shell('tasks.html',t('allIssues'),issues,{active:'issues',className:'wide-container'}));
 const discussionCategories=[['questions','q-a','Q&A'],['experiences','general','General'],['proposals','ideas','Ideas'],['announcements','announcements','Announcements']];
 const discussions=`<div class="discussion-intro"><div><h1>${t('discussions')}</h1><p>${t('discussionHint')}</p></div>${button(deployment.repository_url+'/discussions/new',t('newDiscussion'),true)}</div><div class="discussions-layout"><aside class="discussion-sidebar"><h2>${t('categories')}</h2>${['all','questions','experiences','proposals','announcements'].map((k,i)=>`<button data-discussion-filter="${k}" aria-pressed="${i===0}">${icon(i?'discuss':'repo')}${t(k)}</button>`).join('')}<a class="discussion-guide" href="discussion-guide.html">${t('discussionGuide')}</a></aside><section class="discussion-list"><a class="discussion-row" data-discussion-row data-category="proposals" href="${deployment.discussion_url}">${icon('discuss',21)}<div><h2>${t('trialDiscussion')}</h2><p>${t('trialDiscussionMeta')}</p></div></a>${discussionCategories.map(([cat,slug,name])=>`<a class="discussion-row" data-discussion-row data-category="${cat}" href="${deployment.repository_url}/discussions/categories/${slug}">${icon('discuss',21)}<div><h2>${name} · ${t(cat)}</h2><p>${t('topicMeta')}</p></div></a>`).join('')}</section></div>`;
 fs.writeFileSync(path.join(dir,'discussions.html'),shell('discussions.html',t('discussions'),discussions,{active:'discussions',className:'container'}));
 const board=`<div class="section-title"><div><h1>${t('board')}</h1><p class="page-hint">${t('boardHint')}</p></div>${button(deployment.project_url,t('openBoard'),true)}</div><div class="board-grid">${['statusConfirm','statusReady','statusProgress','statusFeedback','statusDone','statusHold'].map((k,i)=>`<section class="board-column"><h2><span class="status-dot status-${i}"></span>${t(k)}<span class="counter">${i===0?tasks.length:0}</span></h2>${i===0?tasks.map(x=>`<a class="board-card" href="${x.id.toLowerCase()}.html"><small>${icon('issue')}${x.id} · #${x.issue_number}</small><strong>${escape(x.title)}</strong><span class="label label-${x.categoryKey}">${escape(x.category)}</span></a>`).join(''):`<p class="board-empty">${t('noItems')}</p>`}</section>`).join('')}</div>`;
 fs.writeFileSync(path.join(dir,'board.html'),shell('board.html',t('board'),board,{active:'projects',className:'wide-container board-container'}));
 const orgItems=activity.items.filter(x=>x.repository!=='OpenRDHub/community');
 const activityRows=items=>items.map(x=>`<article class="repository-row"><h2><a href="${escape(x.url)}" target="_blank" rel="noopener noreferrer">${escape(x.repository)}#${x.number} · ${escape(x.title)}</a><span class="badge">${x.type==='pr'?'PR':'Issue'}${x.draft?' · Draft':''}</span></h2><p>${t('receiver')}: <code>${escape(x.repository)}</code>${x.base?' · '+escape(x.base):''} · ${t('snapshotStatus')}: ${escape(x.state)}</p><p>${t('assignees')}: ${escape(x.assignees.join(', ')||t('unassigned'))}</p></article>`).join('');
 const orgBoard=`<div class="section-title"><div><h1>${t('orgBoard')}</h1><p class="page-hint">${t('orgBoardHint')}</p><p>${t('repoVerified')} ${escape(activity.verified_on)}</p></div>${button('board.html',t('board'))}</div><div class="repository-list">${activityRows(orgItems)}</div><p><a href="https://github.com/orgs/OpenRDHub/projects" target="_blank" rel="noopener noreferrer">${t('githubProjects')}</a></p>`;
 fs.writeFileSync(path.join(dir,'org-board.html'),shell('org-board.html',t('orgBoard'),orgBoard,{context:'org',active:'projects',className:'container'}));
 fs.writeFileSync(path.join(dir,'org-discussions.html'),shell('org-discussions.html',t('discussions'),`<div class="empty-large">${icon('discuss',44)}<h1>${t('orgDiscussionTitle')}</h1><p>${t('orgDiscussionHint')}</p>${button('routing.html',t('routing'))} ${button(deployment.organization_discussions_url,t('discussionProposal'))}</div>`,{context:'org',active:'discussions',className:'container'}));
 const communityPulls=activity.items.filter(x=>x.repository==='OpenRDHub/community'&&x.type==='pr');
 const pulls=`<div class="empty-large">${icon('pull',44)}<h1>${t('pullEmpty')}</h1><p>${t('pullHint')}</p>${button('community.html',t('seeFiles'))}</div>`;
 fs.writeFileSync(path.join(dir,'pulls.html'),shell('pulls.html',t('pulls'),communityPulls.length?`<h1>${t('pulls')}</h1><p class="page-hint">${t('activitySnapshot')}</p>${activityRows(communityPulls)}`:pulls,{active:'pulls',className:'container'}));
 const repos=repositorySnapshot.repositories;
 const repoPage=`<div class="org-grid"><section class="repo-catalog"><h1 class="page-heading">${t('repositories')} <span class="counter">${repos.length}</span></h1><p class="page-hint">${t('orgRepositoriesHint')}</p><p class="repo-catalog-links"><a href="${repositorySnapshot.source}" target="_blank" rel="noopener noreferrer">${t('repoSource')} ${icon('arrow')}</a><a href="projects.html">${t('repoMapping')}</a></p><label class="issue-search">${icon('search')}<input type="search" id="repo-search" aria-label="${t('repoSearch')}" placeholder="${t('repoSearch')}"></label><p class="page-hint">${t('repoActiveCount')} <strong id="repo-count">${repos.length}</strong> ${t('repoOf')} ${repos.length} · ${t('repoVerified')} ${repositorySnapshot.verified_on}</p><div class="repository-list">${repos.map(repo=>{const desc=locale==='en'?repo.description_en:(repo.description||t('repoOriginalDescription'));return `<article class="repository-row" data-repo-row data-repo-name="${escape(repo.name)}" data-search="${escape(repo.name+' '+desc)}"><h2><a href="${repo.html_url}" target="_blank" rel="noopener noreferrer">${escape(repo.name)}</a><span class="badge">${t('repoPublic')}</span>${repo.fork?`<span class="badge">${t('repoFork')}</span>`:''}</h2><p>${escape(desc)}</p><small>${t('repoBranch')}: <code>${escape(repo.default_branch)}</code>${repo.parent?` · ${t('repoForkFrom')} <a href="${repo.parent.html_url}" target="_blank" rel="noopener noreferrer">${escape(repo.parent.full_name)}</a>`:''}</small>${repo.stage?`<p class="repo-stage">${escape(locale==='en'?repo.stage_en:repo.stage)}</p>`:''}<div class="repo-catalog-links">${repo.intake_url?`<a href="${repo.intake_url}" target="_blank" rel="noopener noreferrer">${escape(locale==='en'?repo.intake_label_en:repo.intake_label)}</a>`:''}${repo.pr_url?`<a href="${repo.pr_url}" target="_blank" rel="noopener noreferrer">${t('viewPulls')}</a>`:''}</div></article>`;}).join('')}<p id="empty-repos" hidden>${t('noResults')}</p></div><section class="proposed-repo"><h2>${t('repoProposed')}</h2><p>${t('repoProposedNote')}</p><a href="community.html" class="button">${icon('repo')} community</a></section></section>${about(true)}</div>`;
 fs.writeFileSync(path.join(dir,'repositories.html'),shell('repositories.html',t('repositories'),repoPage,{context:'org',active:'repositories',className:'container'}));
 const peopleSrc=sourcePath('community/MAINTAINERS.md');
 fs.writeFileSync(path.join(dir,'people.html'),shell('people.html',t('people'),`<div class="org-grid"><div>${mdPanel(peopleSrc,fs.readFileSync(sourceFile(peopleSrc),'utf8'))}</div>${about(true)}</div>`,{context:'org',active:'people',className:'container'}));
 const allFiles=defs.filter(x=>!['org','orgfile'].includes(x[3])).map(([href,src,key,kind])=>({href,src:sourcePath(src),title:kind==='issue'?tasks.find(x=>x.id===key).title:t(key),folder:src.includes('/templates/')?'records-templates':src.includes('/docs/')?'docs':src.includes('/tasks/')?'tasks':'root'}));
 const templateNames=['proposal','need','resource'];
 const templates=templateNames.map(k=>({href:prefix+'raw/'+sourcePath('community/.github/ISSUE_TEMPLATE/'+k+'.md'),src:sourcePath('community/.github/ISSUE_TEMPLATE/'+k+'.md'),title:forms[k].name,folder:'templates'}));
 templates.push({href:prefix+'raw/'+sourcePath('community/.github/PULL_REQUEST_TEMPLATE.md'),src:sourcePath('community/.github/PULL_REQUEST_TEMPLATE.md'),title:t('prTemplate'),folder:'templates'});
 const filesPage=`<div class="section-title"><h1>${t('files')}</h1>${button(prefix+'assets/community-drafts.zip',t('downloadZip'))}</div><label class="issue-search">${icon('search')}<input id="file-search" type="search" aria-label="${t('fileSearch')}" placeholder="${t('fileSearch')}"></label><div class="all-file-list">${[...allFiles,...templates].map(x=>`<a data-file-row data-folder="${x.folder}" data-search="${escape(x.src+' '+x.title)}" href="${x.href}">${icon('file')}<code>${escape(x.src.replace('community/',''))}</code><span>${escape(x.title)}</span></a>`).join('')}<p class="empty-state" id="empty-files" hidden>${t('tableNoFiles')}</p></div>`;
 fs.writeFileSync(path.join(dir,'files.html'),shell('files.html',t('files'),filesPage,{className:'container'}));
 const form=`<div class="section-title form-page-title"><h1 id="form-heading">${t('formHeading')}</h1><span class="badge">${t('draft')}</span></div><p class="page-hint">${t('formHint')}</p><p class="page-hint" id="draft-destination"></p><div class="form-layout"><form id="draft-form"><label class="field"><span>${t('draftType')}</span><select id="draft-type" name="type">${Object.entries(forms).map(([key,x])=>`<option value="${key}">${x.name}</option>`).join('')}</select></label><label class="field"><span>${t('title')} <small>${t('required')}</small></span><input id="draft-title" name="title" maxlength="160" required placeholder="${t('titleHint')}"></label><div id="dynamic-fields"></div><button class="button primary" type="submit">${t('generate')}</button><p class="form-note">${t('formPrivacy')}</p></form><section class="draft-output" aria-labelledby="output-heading"><div class="output-heading"><h2 id="output-heading">${t('markdownDraft')}</h2><span id="draft-status">${t('waiting')}</span></div><p id="draft-empty">${t('draftEmpty')}</p><pre id="draft-result" hidden></pre><div class="output-actions"><button type="button" class="button" id="copy-draft" disabled>${t('copy')}</button><button type="button" class="button" id="download-draft" disabled>${t('downloadMd')}</button></div><p id="copy-status" role="status"></p></section></div>`;
 fs.writeFileSync(path.join(dir,'form.html'),shell('form.html',t('formHeading'),form,{active:'issues',className:'container form-container'}));
 const review=`<article class="markdown readme-panel standalone-doc"><h1>${t('reviewTitle')}</h1><p>${t('reviewIntro')}</p><ol>${t('reviewList').map(x=>`<li>${x}</li>`).join('')}</ol><h2>${t('reviewPending')}</h2><p>${t('reviewPendingText')}</p><p>${t('reviewBoundary')}</p><p>${button('index.html',t('orgHome'))} ${button('community.html',t('communityHome'))}</p></article>`;
 fs.writeFileSync(path.join(dir,'review.html'),shell('review.html',t('review'),review,{className:'container'}));
 fs.writeFileSync(path.join(dir,'data.json'),JSON.stringify({forms,tasks},null,2));
}
function copyMarkdown(root,dest){for(const ent of fs.readdirSync(root,{withFileTypes:true})){if(['web','node_modules','.git'].includes(ent.name))continue;const from=path.join(root,ent.name),to=path.join(dest,ent.name);if(ent.isDirectory())copyMarkdown(from,to);else if(/\.(md|ya?ml)$/.test(ent.name)){fs.mkdirSync(path.dirname(to),{recursive:true});fs.copyFileSync(from,to);}}}
copyMarkdown(communityRoot,path.join(site,'raw','community'));
copyMarkdown(splitLayout?path.join(drafts,'.github'):path.join(base,'organization-profile'),path.join(site,'raw','.github'));
for(const asset of materials.attachments){const dest=path.join(site,'raw',asset.src);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(asset.file,dest);}
for(const name of ['style.css','app.js'])fs.copyFileSync(path.join(base,name),path.join(site,name));
const manifest=JSON.stringify({pages:defs,extraFiles,routes,locales:['zh','en']},null,2);
fs.writeFileSync(path.join(site,'page-manifest.json'),manifest);
if(!process.env.SITE_OUTPUT)fs.writeFileSync(path.join(base,'page-manifest.json'),manifest);
console.log(`Built ${(defs.length+extraFiles.length)*2} localized pages from ${defs.length*2} localized Markdown documents.`);

execFileSync(process.env.PYTHON||'python3',['-c',`from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED
import sys
root=Path(sys.argv[1]);archive=Path(sys.argv[2])
archive.parent.mkdir(parents=True,exist_ok=True)
with ZipFile(archive,'w',ZIP_DEFLATED) as z:
 for p in sorted(root.rglob('*')):
  if p.is_file():
   z.write(p,Path('community')/p.relative_to(root))
`,path.join(site,'raw','community'),path.join(site,'assets/community-drafts.zip')]);
const oldSite=targetSite+'.previous-'+process.pid;
if(fs.existsSync(targetSite))fs.renameSync(targetSite,oldSite);
try{fs.renameSync(site,targetSite);}catch(error){if(fs.existsSync(oldSite))fs.renameSync(oldSite,targetSite);throw error;}
if(fs.existsSync(oldSite))fs.rmSync(oldSite,{recursive:true,force:true});
console.log('Built validated local preview and document ZIP.');
