export function libraryUI({t,records,icon,escape,render}) {
 const categories=['all','proposal','guide','reference','meeting','discussion','decision','daily'];
 const count=records.filter(r=>!r.example).length;
 return `<div class="library-heading"><div><p class="library-eyebrow">community / knowledge</p><h1>${t('libraryTitle')}</h1><p>${t('librarySubtitle')}</p></div><a class="button primary" href="knowledge-plan.html">${t('viewPlan')} ${icon('arrow')}</a></div>
 <div class="library-intro"><div><strong>${t('wechatStage')}</strong><span>${t('wechatStageText')}</span></div><span>${icon('arrow')}</span><div><strong>${t('feishuStage')}</strong><span>${t('feishuStageText')}</span></div><span>${icon('arrow')}</span><div><strong>${t('githubStage')}</strong><span>${t('githubStageText')}</span></div><span>${icon('arrow')}</span><div><strong>${t('webStage')}</strong><span>${t('webStageText')}</span></div></div>
 <div class="library-layout"><aside class="library-sidebar"><h2>${t('libraryBrowse')}</h2>${categories.map(k=>`<button data-library-type="${k}" aria-pressed="${k==='all'}">${icon(k==='meeting'?'people':k==='discussion'?'discuss':k==='decision'?'check':'file')}<span>${t('recordType_'+k)}</span></button>`).join('')}<div class="side-divider"></div><a href="record-policy.html">${t('recordPolicy')}</a><h2>${t('recordTemplates')}</h2>${['meeting','discussion','daily','decision'].map(k=>`<a href="template-${k}.html">${t('recordType_'+k)} ${icon('arrow')}</a>`).join('')}</aside>
 <section class="library-main"><div class="library-tools"><label class="issue-search">${icon('search')}<input id="library-search" type="search" placeholder="${t('librarySearch')}" aria-label="${t('librarySearch')}"></label><select id="library-sort" aria-label="${t('librarySort')}"><option value="updated">${t('sortUpdated')}</option><option value="date">${t('sortDate')}</option></select></div><div class="library-filter-note"><span><b id="library-count">${count}</b> ${t('libraryCount')}</span><label><input type="checkbox" id="show-examples">${t('showExamples')}</label></div><p class="library-local-note">${t('libraryLocalNote')}</p><div class="library-records">${records.map(r=>`<article class="library-record" data-library-record data-type="${r.type}" data-example="${r.example}" data-updated="${r.updated}" data-date="${r.date}" data-search="${escape(r.title+' '+r.summary+' '+r.id+' '+r.source+' '+r.body)}" ${r.example?'hidden':''}><div class="library-record-icon">${icon(r.type==='meeting'?'people':r.type==='discussion'?'discuss':r.type==='decision'?'check':'file',18)}</div><div><div class="record-overline"><span>${t('recordType_'+r.type)}</span><span class="badge ${r.example?'example-badge':''}">${t(r.example?'example':'localRecord')}</span></div><h2><a href="${r.route}">${escape(r.title)}</a></h2><p>${escape(r.summary)}</p><div class="record-meta"><span>${r.id}</span><span>${t('recordUpdated')} ${r.updated}</span><span>${t('recordStatus_'+r.status)}</span>${r.translationFallback?`<span>${t('original_'+r.lang)}</span>`:''}</div></div>${icon('arrow')}</article>`).join('')}<div class="library-empty" id="empty-library" hidden><h2>${t('libraryEmpty')}</h2><p>${t('libraryEmptyHint')}</p><a href="template-meeting.html">${t('viewTemplates')}</a></div></div></section></div>`;
}
export function recordIntro({record:r,t,icon,escape}) {
 const linked=(value,url)=>url?`<a href="${escape(url)}" target="_blank" rel="noopener noreferrer">${escape(value)}</a>`:escape(value);
 const source=r.source==='illustrative'?t('recordSourceExample'):r.source==='local-proposal'?t('recordSourceLocal'):r.source;
 const field=(key,value)=>`<div><dt>${t(key)}</dt><dd>${value}</dd></div>`;
 const meta=field('recordId',escape(r.id))+field('recordUpdated',escape(r.updated))+field('recordStatus',t('recordStatus_'+r.status))+field('recordAuthority',linked(r.authority==='feishu'?'Feishu / 飞书':'GitHub',r.authority_url))+field('recordReviewer',escape(r.reviewer==='unassigned'?t('unassigned'):r.reviewer))+field('recordSource',linked(source,r.source_url))+field('recordRevision',escape(r.source_revision))+field('recordVisibility',t('visibility_'+r.visibility))+field('recordScope',t('publication_'+r.publication));
 return `<a class="record-back" href="knowledge.html">← ${t('libraryTitle')}</a>${r.translationFallback?`<p class="translation-notice" role="note">${t('original_'+r.lang)} · ${t('translationPending')}</p>`:''}<div class="record-summary"><div><span class="badge">${t('recordType_'+r.type)}</span> <span class="badge ${r.example?'example-badge':''}">${t(r.example?'example':'localRecord')}</span></div><dl>${meta}</dl><p>${t(r.example?'exampleNotice':'recordMetadataNotice')}</p></div>`;
}
